modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/MattCzyr/NaturesCompass/issues"
license="CC BY-NC-SA 4.0"

[[mods]]
    modId="naturescompassedited"
    version="${file.jarVersion}"
    displayName="Nature's Compass Edited"
    displayURL="https://github.com/MCMostWolf/NaturesCompassEdited"
    authors="ChaosTheDude"
    description='''
    Search for a biome and get information about it.
    Edited by MCMostWolf
    '''

[[dependencies.naturescompass]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
